"""
Django settings for  project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*8r!l)8u3!=+@&ruco=1ax+!626=+v=qk%4v$$2(h+fqglfhat'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'main'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pythonready.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
       # 'libraries':{
       #      'main': 'main.templatetags.main',
       #      }
        },
    },
]

WSGI_APPLICATION = 'pythonready.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

if os.path.isdir("/home/kutuma/webapps"):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pythonready',
            'USER': 'pythonready',
            'PASSWORD': 'abtree971',
            #'HOST': '/Applications/MAMP/tmp/mysql/mysql.sock',   # Or an IP Address that your DB is hosted on
            #'PORT': '3306',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pythonready',
            'USER': 'root',
            'PASSWORD': 'root',
            'HOST': '/Applications/MAMP/tmp/mysql/mysql.sock',   # Or an IP Address that your DB is hosted on
            #'PORT': '3306',
        }
}



# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


if os.path.isdir("/home/kutuma/webapps"):
    STATIC_URL="http://pythonready.com/static/"
    #STATIC_PATH = '/home/kutuma/webapps/pythonready_static'
else:
    STATIC_URL = '/static/'                                     # the shortcut to reference STATIC_PATH in your code

STATIC_ROOT = '/home/kutuma/webapps/pythonready_static'        # the place stuff is copied to after collectstatic is run on LIVE
STATIC_PATH = os.path.join(BASE_DIR, "static")              # the path where stuff is actually housed
STATICFILES_DIRS = (
   STATIC_PATH,
)

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.webfaction.com'
#EMAIL_PORT = 587
EMAIL_HOST_USER = 'ryzotechhayden_mail'
EMAIL_HOST_PASSWORD = 'abtree971'
EMAIL_ADMIN = 'beastflow@gmail.com'
EMAIL_DEFAULT_FROM = 'hayden@ryzotech.com'

MODULE_PATH = os.path.join(BASE_DIR, "lib")
sys.path.append(MODULE_PATH)

MEDIA_URL = '/images/'
APPEND_SLASH=False

TINYMCE_DEFAULT_CONFIG = {
    'images_upload_base_path': '/static/images/'
    ,'image_prepend_url': "/static/images/"
    ,'image_uploadtab': True
    ,'file_picker_types': 'file image media'
    ,'automatic_uploads': True
    ,'menubar': ""
    ,'height': 700
    ,'plugins': [ 'codesample', 'lists', "advlist", 'code', 'image']
    ,'codesample_global_prismjs': True
    ,'codesample_languages': [
    { 'text': 'HTML/XML', 'value': 'markup' },
    { 'text': 'Python', 'value': 'python' },
    { 'text': 'Bash', 'value': 'bash' },
  ]
    ,'toolbar': 'formatselect | undo redo | styleselect | bold italic | link image | lists | codesample | numlist | code | cut paste'
    ,'formats': {
        'h1': { 'block': 'h1', 'classes': 'heading' },
    }
    ,'style_formats': [{
        'title': 'ordered-list'
        ,'selector': 'li'
        ,'classes': 'highlight'
    }
    ,{'title': 'image-left'
        ,'selector': 'img'
        ,'classes': 'figure-left'
    }
    ,{'title': 'image-right'
        ,'selector': 'img'
        ,'classes': 'figure-right'
    }
    ,{'title': 'image-center'
        ,'selector': 'img'
        ,'classes': 'figure-center'
    }
    ,{'title': 'caption'
        ,'selector': 'p'
        ,'classes': 'caption'
    }
    ,{'title': 'output'
        ,'selector': 'p'
        ,'classes': 'output'
    }
    ]

  }
