# Generated by Django 3.0.5 on 2020-06-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lecture_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
